In [1]:
from manim import *
from random import seed, shuffle
import numpy as np

Manim Community v0.17.1

## Probability via simulation

In [2]:
%%manim -v WARNING --progress_bar None NG_01_02_ProbViaSim

seed(15)

class NG_01_02_ProbViaSim(Scene):

    def construct(self):
        scale = 0.2
        POS_COLOR = BLUE
        NEG_COLOR = RED
        SICK_SYMB = "X"
        WELL_SYMB = "O"
        # SICK_SYMB = "☹︎"
        # WELL_SYMB = "☺︎"
        sick_icon = Text(SICK_SYMB).scale(5) # or ♓︎
        # sick_icon = Triangle()
        well_icon = Text(WELL_SYMB).scale(5)

        targetspace = Axes(
            y_range=[0, 1.0, 0.1],
            x_range=[0, 1.0, 0.1],
            y_length=4,
            x_length=4,
            # x_axis_config={"font_size": 36},
        )
        targetspace.shift(4*LEFT)
        self.add(targetspace)

        def as_rectangle_corners(bottom_left, top_right):
            return [
                (top_right[0], top_right[1]),
                (bottom_left[0], top_right[1]),
                (bottom_left[0], bottom_left[1]),
                (top_right[0], bottom_left[1]),
            ]
        
        def get_rectangle(bottom_left, top_right, color=POS_COLOR):
            polygon = Polygon(
                *[
                    targetspace.c2p(*i)
                    for i in as_rectangle_corners(
                        bottom_left, top_right
                    )
                ]
            )
            polygon.stroke_width = 1
            polygon.set_fill(color, opacity=0.3)
            polygon.set_stroke(color)
            return polygon

        def in_zone(zone, point):
            return (
                zone[0][0] <= point[0] < zone[1][0]
                and zone[0][1] <= point[1] < zone[1][1]
            )
        
        well_neg_zone = (0.0, 0.0), (0.9, 0.9)
        well_neg_rect = get_rectangle(*well_neg_zone, NEG_COLOR)
        self.add(well_neg_rect)
        well_pos_zone = (0.9, 0.0), (1.0, 0.9)
        well_pos_rect = get_rectangle(*well_pos_zone, POS_COLOR)
        self.add(well_pos_rect)
        sick_neg_zone = (0.0, 0.9), (0.9, 1.0)
        sick_neg_rect = get_rectangle(*sick_neg_zone, NEG_COLOR)
        self.add(sick_neg_rect)
        sick_pos_zone = (0.9, 0.9), (1.0, 1.0)
        sick_pos_rect = get_rectangle(*sick_pos_zone, POS_COLOR)
        self.add(sick_pos_rect)

        zones = [well_neg_zone, well_pos_zone, sick_neg_zone, sick_pos_zone]
        count = np.array([0, 0, 0, 0])

        def zone(point):
            for i, zone in enumerate(zones):
                if in_zone(zone, point):
                    return i, zone

        chart = BarChart(
            values=[0,0,0,0],
            bar_names=[ WELL_SYMB, WELL_SYMB, SICK_SYMB, SICK_SYMB],
            bar_colors=[NEG_COLOR, POS_COLOR, NEG_COLOR, POS_COLOR],
            y_range=[0, 1.0, 0.1],
            y_length=6,
            x_length=4,
            # x_axis_config={"font_size": 36},
        )
        chart.shift(4*RIGHT)
        c_bar_lbls = chart.get_bar_labels(font_size=24)
        self.add(chart, c_bar_lbls)

        for i in range(100):
            p = np.random.random(2)
            print(p, targetspace.c2p(*p))
            self.add(
                Dot(
                    targetspace.c2p(*p)
                ))
            i, z = zone(p)
            count[i] += 1
            self.play(
                chart.animate.change_bar_values(count/count.sum()),
                run_time=0.5/(i+1)**2)
            # c_bar_lbls = chart.get_bar_labels(font_size=24)
            # self.play(
            #     Transform(c_bar_lbls, chart.get_bar_labels(font_size=24)),
            #     run_time=0.5/(i+1)**2
            # )



[0.33948709 0.36287449] [-4.64205163 -0.54850203  0.        ]
[1 0 0 0] [1. 0. 0. 0.]
[5.16340267e-01 3.75798919e-04] [-3.93463893 -1.9984968   0.        ]
[2 0 0 0] [1. 0. 0. 0.]
[0.43622517 0.47424311] [-4.25509931 -0.10302756  0.        ]
[3 0 0 0] [1. 0. 0. 0.]
[0.91572286 0.69709583] [-2.33710856  0.78838332  0.        ]
[3 1 0 0] [0.75 0.25 0.   0.  ]
[0.34634942 0.94876878] [-4.61460232  1.79507513  0.        ]
[3 1 1 0] [0.6 0.2 0.2 0. ]
[0.69257741 0.45084785] [-3.22969034 -0.1966086   0.        ]
[4 1 1 0] [0.66666667 0.16666667 0.16666667 0.        ]
[0.42559901 0.86981383] [-4.29760395  1.4792553   0.        ]
[5 1 1 0] [0.71428571 0.14285714 0.14285714 0.        ]
[0.17671375 0.29420826] [-5.293145   -0.82316694  0.        ]
[6 1 1 0] [0.75  0.125 0.125 0.   ]
[0.82152745 0.72893204] [-2.71389018  0.91572817  0.        ]
[7 1 1 0] [0.77777778 0.11111111 0.11111111 0.        ]
[0.76773998 0.99028765] [-2.92904007  1.96115059  0.        ]
[7 1 2 0] [0.7 0.1 0.2 0. ]
[0.68673